-- Hosted Postgres regression, run as the migration owner. Everything is rolled
-- back, including two synthetic users. No Auth session, email, VM or AI call.
-- Payloads are real strings, not forged counters. Repeated text compresses on
-- disk; quota accounting intentionally measures serialized, uncompressed bytes.
begin;
set local statement_timeout = '60s';
do $$
declare
  owner_id uuid := gen_random_uuid(); other_id uuid := gen_random_uuid();
  v_project_id uuid; fifth_project uuid; other_project uuid; first_submission jsonb;
  final_submission jsonb; other_submission jsonb; source_id uuid; fixture_id uuid;
  manifest jsonb := '{"id":"practice-storage-test","title":"Storage regression","concepts":["arrays"],"source":"curated"}';
  filler_manifest jsonb := '{"id":"practice-storage-test","title":"Storage regression","concepts":["arrays"],"padding":""}';
  source_version jsonb; used_bytes bigint; source_bytes bigint; metadata_charge bigint;
  remaining bigint; chunk_bytes integer; filler_base integer; before_count integer;
  attempted uuid; i integer; client_role text; relation_name text;
  grading_plan jsonb; grading_receipt jsonb; grading_bytes bigint;
begin
  foreach client_role in array array['anon','authenticated'] loop
    assert not has_function_privilege(client_role,'public.begin_activity_submission(uuid,uuid,uuid,jsonb,text,text,text)','EXECUTE'),
      'Browser role can call submission writer';
    assert not has_function_privilege(client_role,'public.record_submission_assessment(uuid,uuid,integer,boolean,boolean,jsonb,text)','EXECUTE'),
      'Browser role can write a grade';
    foreach relation_name in array array['public.activity_submissions','public.submission_sources'] loop
      assert not has_table_privilege(client_role,relation_name,'INSERT,UPDATE,DELETE'),'Browser role can mutate immutable evidence';
      assert (select relrowsecurity from pg_class where oid=relation_name::regclass),'Evidence RLS is disabled';
    end loop;
  end loop;
  insert into auth.users(id,email) values
    (owner_id,'storage-'||owner_id||'@example.invalid'),
    (other_id,'storage-'||other_id||'@example.invalid');

  for i in 1..4 loop
    insert into public.projects(user_id,title,activity_id,language)
      values(owner_id,'Disposable evidence quota '||i,manifest->>'id','JavaScript') returning id into v_project_id;
    perform public.save_source_revision_batch(owner_id,v_project_id,
      jsonb_build_array(jsonb_build_object('path','main.js','content',E'quoted " slash \\ newline \n 😀','revision',0)));
    first_submission:=public.begin_activity_submission(owner_id,v_project_id,gen_random_uuid(),manifest,'JavaScript','test/model','😀');
    source_id:=(first_submission->>'source_id')::uuid;
    source_version:=first_submission->'source_versions';
    metadata_charge:=octet_length(manifest::text)+octet_length(source_version::text)+octet_length('😀');
    assert (first_submission->>'metadata_bytes')::integer=metadata_charge,'Generated metadata counts must include UTF-8 bytes';
    select storage_bytes into source_bytes from public.submission_sources where id=source_id;
    assert (select storage_bytes=octet_length(files::text) and storage_bytes>byte_size from public.submission_sources where id=source_id),
      'Source quota must include JSON escaping, not just content length';
    grading_plan:=jsonb_build_object('version',1,'checkVersion','quota-v1','activityId',manifest->>'id','language','JavaScript',
      'sourceDigest',(select digest from public.submission_sources s where s.id=source_id),'harnessDigest',repeat('a',64),'runtimeDigest',repeat('b',64),
      'cases',(select jsonb_agg(jsonb_build_object('input',n,'label','Quota fixture')) from generate_series(1,24) n));
    grading_receipt:=public.prepare_submission_grading(owner_id,(first_submission->>'id')::uuid,grading_plan);
    select reserved_bytes into grading_bytes from private.submission_grading where submission_id=(first_submission->>'id')::uuid;
    assert grading_bytes=octet_length(grading_plan::text)+131072,'Report capacity must be reserved before execution';
    begin
      update public.activity_submissions set metadata_bytes=1 where id=(first_submission->>'id')::uuid;
      raise exception 'Generated byte counters accepted a forged write';
    exception when generated_always then null; end;

    -- Leave exactly enough room for ONE deduplicated submission. These fixture
    -- rows use the service/migration role only; browser roles have no writes.
    remaining:=52428800-source_bytes-metadata_charge-metadata_charge-grading_bytes;
    filler_base:=octet_length(filler_manifest::text)+octet_length(source_version::text);
    while remaining>0 loop
      chunk_bytes:=least(900000,remaining);
      if remaining>chunk_bytes and remaining-chunk_bytes<filler_base then chunk_bytes:=chunk_bytes-filler_base; end if;
      assert chunk_bytes>=filler_base,'Invalid fixture remainder';
      insert into public.activity_submissions(id,user_id,project_id,source_id,source_versions,activity_id,manifest,language,model_id)
        values(gen_random_uuid(),owner_id,v_project_id,source_id,source_version,manifest->>'id',
          jsonb_set(filler_manifest,'{padding}',to_jsonb(repeat('x',chunk_bytes-filler_base))),'JavaScript','test/model')
        returning id into fixture_id;
      remaining:=remaining-chunk_bytes;
    end loop;
    final_submission:=public.begin_activity_submission(owner_id,v_project_id,gen_random_uuid(),manifest,'JavaScript','test/model','😀');
    assert final_submission->>'source_id'=first_submission->>'source_id','Unchanged files must deduplicate';
    used_bytes:=source_bytes+grading_bytes+(select sum(s.metadata_bytes) from public.activity_submissions s where s.project_id=v_project_id);
    assert used_bytes=52428800,'Boundary submission must reach the exact project quota';
    assert public.prepare_submission_grading(owner_id,(first_submission->>'id')::uuid,grading_plan)=grading_receipt,'Idempotent plan retry must work at quota';
    begin
      perform public.prepare_submission_grading(owner_id,(final_submission->>'id')::uuid,grading_plan);
      raise exception 'Grading plan bypassed quota';
    exception when raise_exception then if sqlerrm<>'SUBMISSION_STORAGE_LIMIT' then raise; end if; end;
    assert not exists(select 1 from private.submission_grading where submission_id=(final_submission->>'id')::uuid),'Rejected plan leaked evidence';
    -- This maximum-size supported report would fail at quota without the
    -- reservation. JSON is under the private 128 KiB bound.
    perform public.finish_submission_grading(owner_id,(first_submission->>'id')::uuid,grading_receipt->>'planDigest',
      jsonb_build_object('compileFailure',null,'cases',(select jsonb_agg(jsonb_build_object('output',repeat('x',5000),'failure',null,'passed',true)) from generate_series(1,24))));
    perform public.record_submission_assessment(owner_id,(first_submission->>'id')::uuid,100,true,false,'["Quota fixture"]','command');
    select count(*) into before_count from public.activity_submissions s where s.project_id=v_project_id;
    attempted:=gen_random_uuid();
    begin
      perform public.begin_activity_submission(owner_id,v_project_id,attempted,manifest,'JavaScript','test/model','😀');
      raise exception 'Duplicate source bypassed the metadata quota';
    exception when raise_exception then
      if sqlerrm<>'SUBMISSION_STORAGE_LIMIT' then raise; end if;
    end;
    assert (select count(*) from public.activity_submissions s where s.project_id=v_project_id)=before_count,'Rejected submission must not write a record';
    assert not exists(select 1 from public.activity_submissions where id=attempted),'Rejected request leaked a submission';
    assert public.begin_activity_submission(owner_id,v_project_id,(final_submission->>'id')::uuid,manifest,'JavaScript','test/model','😀')=final_submission,
      'Idempotent retry must still work at quota';
    perform public.save_source_revision_batch(owner_id,v_project_id,'[{"path":"main.js","content":"changed source","revision":1}]');
    begin
      perform public.begin_activity_submission(owner_id,v_project_id,gen_random_uuid(),manifest,'JavaScript','test/model','😀');
      raise exception 'New source bypassed the evidence quota';
    exception when raise_exception then
      if sqlerrm<>'SUBMISSION_STORAGE_LIMIT' then raise; end if;
    end;
    assert (select count(*) from public.submission_sources s where s.project_id=v_project_id)=1,'Quota rejection must not leave an orphan source';
    -- Finalizing existing work remains possible at capacity; no source rewrite.
    perform public.record_submission_assessment(owner_id,(final_submission->>'id')::uuid,85,true,true,'["Synthetic test feedback"]','rubric');
    assert (select state from public.activity_submissions where id=(final_submission->>'id')::uuid)='complete','Generated counters blocked finalization';
    assert (select metadata_bytes from public.activity_submissions where id=(final_submission->>'id')::uuid)=metadata_charge,'Finalization changed metadata charge';
  end loop;

  insert into public.projects(user_id,title,activity_id,language)
    values(owner_id,'Disposable fifth project',manifest->>'id','JavaScript') returning id into fifth_project;
  perform public.save_source_revision_batch(owner_id,fifth_project,'[{"path":"main.js","content":"new account source","revision":0}]');
  begin
    perform public.begin_activity_submission(owner_id,fifth_project,gen_random_uuid(),manifest,'JavaScript','test/model');
    raise exception 'Creating a project bypassed the account evidence quota';
  exception when raise_exception then if sqlerrm<>'SUBMISSION_STORAGE_LIMIT' then raise; end if; end;
  assert not exists(select 1 from public.submission_sources where project_id=fifth_project),'Account quota rejection leaked source';

  insert into public.projects(user_id,title,activity_id,language)
    values(other_id,'Disposable independent account',manifest->>'id','JavaScript') returning id into other_project;
  perform public.save_source_revision_batch(other_id,other_project,'[{"path":"main.js","content":"other account","revision":0}]');
  other_submission:=public.begin_activity_submission(other_id,other_project,gen_random_uuid(),manifest,'JavaScript','test/model');
  assert other_submission->>'state'='pending','Another account must retain its own quota';
  perform public.fail_activity_submission(other_id,(other_submission->>'id')::uuid,'TEST_FAILURE');
  assert (select state from public.activity_submissions where id=(other_submission->>'id')::uuid)='failed','Generated counters blocked failure transition';

  -- Deleting ONLY a disposable fixture makes space for a fresh snapshot. All
  -- rows, including this delete, are rolled back at the end of the script.
  delete from public.activity_submissions where id=fixture_id and user_id=owner_id;
  final_submission:=public.begin_activity_submission(owner_id,fifth_project,gen_random_uuid(),manifest,'JavaScript','test/model');
  assert final_submission->>'state'='pending','Freed capacity must permit another submission';
end $$;
rollback;
select 'PASS: source/metadata/grading byte counts, exact project/account quotas, reserved report finalization, no orphan writes, idempotence and account isolation' as result;
