import { challengeLesson } from '../practice/shared'
import { reactLessonFiles } from '../practice/react'

const command={executable:'npm',args:['test','--','--run']}
const preparation='Run npm install, then npm test -- --run for editable interaction checks. npm run dev opens a React preview on port 3000. Submit provides AI-assessed rubric feedback; these local checks are not trusted scoring.'
export const reactChallenges=[
  challengeLesson({track:'react',stage:'transform',title:'Summarize a shopping basket',
    summary:'Render a derived basket total that stays correct when props change, without duplicating state.',concepts:['derived data','React props','formatting'],
    instructions:['Implement App({items}) in src/App.jsx. Each item is {id,name,cents,quantity}; IDs are unique, cents is an integer 0–100000 and quantity is 0–100. Render each positive-quantity item as a list item containing "NAME × QUANTITY" in input order. Do not mutate items.', 'Render exactly one role="status" with "Total: $D.CC", using the sum of cents × quantity and exactly two fractional digits. If no positive-quantity items remain, show "Your basket is empty". New props must update all derived output without remounting.'],
    explanation:'A basket total is a pure projection of its item props. Compute it from the current inputs so later prop changes cannot leave stale state. Integer cents avoid accumulating decimal rounding errors; format only at the presentation boundary.',
    hints:['Keep zero-quantity items out of the list and total.', 'Sum integer cents before formatting dollars.', 'Do not initialize state from items for derived values.'],
    reflectionQuestions:['Why is a stored total easy to make stale?', 'Why should cents remain integers until rendering?'],
    examples:[{input:'Pen: 125 cents × 2; Paper: 50 cents × 1',output:'Pen × 2; Paper × 1; Total: $3.00'}],
    files:reactLessonFiles(`import React from 'react'\nconst initialItems=[{id:'pen',name:'Pen',cents:125,quantity:2}]\nexport default function App({items=initialItems}) {\n  throw new Error('Complete the TODO before submitting')\n}\n`, `test('derives ordered basket rows and exact total',()=>{\n  render(<App items={[{id:'b',name:'Pen',cents:125,quantity:2},{id:'a',name:'Paper',cents:50,quantity:1},{id:'z',name:'Hidden',cents:99,quantity:0}]}/>)\n  expect(screen.getAllByRole('listitem').map(x=>x.textContent)).toEqual(['Pen × 2','Paper × 1'])\n  expect(screen.getByRole('status').textContent).toBe('Total: $3.00')\n})\ntest('updates with props, preserves input and handles zero totals',()=>{\n  const items=Object.freeze([Object.freeze({id:'a',name:'Gift',cents:0,quantity:2})])\n  const view=render(<App items={items}/>)\n  expect(screen.getByRole('listitem').textContent).toBe('Gift × 2')\n  expect(screen.getByRole('status').textContent).toBe('Total: $0.00')\n  view.rerender(<App items={[]}/>)\n  expect(screen.queryAllByRole('listitem')).toHaveLength(0)\n  expect(screen.getByText('Your basket is empty')).toBeTruthy()\n  view.rerender(<App items={[{id:'x',name:'Bulk',cents:99999,quantity:100}]}/>)\n  expect(screen.getByRole('status').textContent).toBe('Total: $99999.00')\n})`),command,preparation,
    quality:'Derives all output from current immutable props and formats integer cents at the boundary',
  }),
  challengeLesson({track:'react',stage:'validator',title:'Validate an accessible username form',
    summary:'Show useful validation and submission feedback while keeping keyboard focus and errors predictable.',concepts:['forms','validation','accessibility'],
    instructions:['Implement App({onJoin}) with a text input labeled "Username" and a native submit button named "Join" inside a form. A valid username is 3–12 ASCII letters, digits or underscores, starts with a letter, and is case-sensitive. Do not trim input.', 'Initially show no error. On invalid submit show exactly "Use 3–12 characters, starting with a letter; letters, digits and _ only." in role="alert", set aria-invalid="true", connect that error using aria-describedby, and focus the input. Do not call onJoin.', 'Clear error and aria-invalid on input edits. On valid submit call synchronous onJoin(value) once and show "Joined as VALUE" in role="status". Clear that success status on subsequent input edits. Default onJoin is a no-op. Native form submission must also work with keyboard submission.'],
    explanation:'Validation has both a data contract and an interaction contract. Native form submission provides keyboard behavior; connected error text and focus make a failed attempt understandable. Editing should invalidate old success or error feedback, not leave it attached to a new value.',
    hints:['Use one form onSubmit handler and prevent navigation.', 'Validate the whole string, not a matching substring.', 'Store feedback state and connect the visible error to the input ID.'],
    reflectionQuestions:['Why should editing clear a previous success message?', 'How do role="alert", aria-describedby and focus complement one another?'],
    examples:[{input:'"Ada_7" then Join',output:'onJoin("Ada_7"); Joined as Ada_7'},{input:'" Ada" then Join',output:'Validation error; input focused; no onJoin call'}],
    files:reactLessonFiles(`import React, {useRef,useState} from 'react'\nexport default function App({onJoin=()=>{}}) {\n  throw new Error('Complete the TODO before submitting')\n}\n`, `const errorText='Use 3–12 characters, starting with a letter; letters, digits and _ only.'\ntest.each(['','ab','1abc',' Ada','a-b','abcdefghijklmn'])('rejects %s with a connected error and focus',value=>{\n  const onJoin=vi.fn();render(<App onJoin={onJoin}/>)\n  const input=screen.getByLabelText('Username')\n  expect(screen.queryByRole('alert')).toBeNull()\n  fireEvent.change(input,{target:{value}})\n  fireEvent.submit(input.closest('form'))\n  const error=screen.getByRole('alert')\n  expect(error.textContent).toBe(errorText)\n  expect(input.getAttribute('aria-invalid')).toBe('true')\n  expect(input.getAttribute('aria-describedby')?.split(' ')).toContain(error.id)\n  expect(error.id).not.toBe('')\n  expect(document.activeElement).toBe(input)\n  expect(onJoin).not.toHaveBeenCalled()\n})\ntest('submits once, then clears feedback when editing',()=>{\n  const onJoin=vi.fn();render(<App onJoin={onJoin}/>)\n  const input=screen.getByLabelText('Username')\n  fireEvent.submit(input.closest('form'))\n  fireEvent.change(input,{target:{value:'Ada_7'}})\n  expect(screen.queryByRole('alert')).toBeNull()\n  expect(input.getAttribute('aria-invalid')).not.toBe('true')\n  fireEvent.click(screen.getByRole('button',{name:'Join'}))\n  expect(onJoin).toHaveBeenCalledExactlyOnceWith('Ada_7')\n  expect(screen.getByRole('status').textContent).toBe('Joined as Ada_7')\n  fireEvent.change(input,{target:{value:'New_Name'}})\n  expect(screen.queryByText('Joined as Ada_7')).toBeNull()\n})`),command,preparation,
    quality:'Uses a native form, a connected announced error and predictable focus without duplicate submissions',
  }),
  challengeLesson({track:'react',stage:'performance',title:'Cache a costly derived report',
    summary:'Avoid repeated report computation on unrelated UI updates while recomputing for changed dependencies.',concepts:['memoization','dependency identity','performance'],
    instructions:['Implement App({items,calculate}). items is an immutable array of numbers. Pure calculate(items) returns a finite number. Render its result as "Report: N" in role="status". Add a native button named "Toggle details" and show "Details are open" only when toggled on.', 'Call calculate during the initial report computation. After that, toggling details must not call it again when items and calculate references are unchanged. A new items reference or calculate reference must recompute the report, even when the array values look equal. Do not mutate input or call calculate in an effect.', 'Use React memoization for the derived value, not a global cache or duplicated state. React may invoke pure calculations more than once in development Strict Mode; the requirement concerns avoiding additional calls after the baseline render on unrelated updates.'],
    explanation:'Memoization is useful when a derived calculation is expensive and its dependencies are stable. Every input used by the calculation belongs in the dependency list. An incomplete list produces stale output; a freshly created dependency on every render defeats caching.',
    hints:['Store only whether details are open.', 'Memoize the report using both items and calculate.', 'Measure calls relative to the initial render instead of assuming Strict Mode calls exactly once.'],
    reflectionQuestions:['Why must calculate itself be a dependency?', 'When would memoization cost more than recomputing the value?'],
    examples:[{input:'Same items/calculator, Toggle details twice',output:'Same report; no extra calculate calls'},{input:'Replace calculate with a different pure function',output:'Updated report'}],
    files:reactLessonFiles(`import React, {useMemo,useState} from 'react'\nconst initialItems=[1,2,3]\nconst initialCalculate=items=>items.reduce((sum,n)=>sum+n,0)\nexport default function App({items=initialItems,calculate=initialCalculate}) {\n  throw new Error('Complete the TODO before submitting')\n}\n`, `test('does not recompute for unrelated UI updates',()=>{\n  const items=Object.freeze([1,2,3]),calculate=vi.fn(values=>values.reduce((a,b)=>a+b,0))\n  render(<React.StrictMode><App items={items} calculate={calculate}/></React.StrictMode>)\n  expect(screen.getByRole('status').textContent).toBe('Report: 6')\n  const baseline=calculate.mock.calls.length\n  expect(baseline).toBeGreaterThan(0)\n  fireEvent.click(screen.getByRole('button',{name:'Toggle details'}))\n  expect(screen.getByText('Details are open')).toBeTruthy()\n  fireEvent.click(screen.getByRole('button',{name:'Toggle details'}))\n  expect(screen.queryByText('Details are open')).toBeNull()\n  expect(calculate).toHaveBeenCalledTimes(baseline)\n})\ntest('recomputes for each changed dependency, not equal-value guesses',()=>{\n  const items=Object.freeze([2,3]),calculate=vi.fn(values=>values.reduce((a,b)=>a+b,0))\n  const view=render(<App items={items} calculate={calculate}/>)\n  const count=calculate.mock.calls.length\n  const nextItems=Object.freeze([2,3])\n  view.rerender(<App items={nextItems} calculate={calculate}/>)\n  expect(calculate.mock.calls.length).toBeGreaterThan(count)\n  const nextCalculate=vi.fn(values=>values.length*10)\n  view.rerender(<App items={nextItems} calculate={nextCalculate}/>)\n  expect(nextCalculate).toHaveBeenCalled()\n  expect(screen.getByRole('status').textContent).toBe('Report: 20')\n})`),command,preparation,
    quality:'Uses complete dependency-aware memoization without effects, mutation or a global cache',
  }),
]
