import { compiledRunner, practiceLesson } from './shared'

const command = { executable: 'python3', args: ['check.py'] }
const javaFiles = (source: string, checks: string) => [
  { path: 'Main.java', content: source },
  { path: 'LessonTest.java', content: `import java.util.*;\npublic class LessonTest {\n  static void equal(Object actual, Object expected) {\n    if (!Objects.equals(actual, expected)) throw new AssertionError("Expected " + expected + ", received " + actual);\n  }\n  public static void main(String[] args) {\n${checks}\n    System.out.println("Practice checks passed");\n  }\n}\n` }, compiledRunner('Java'),
]
const cppFiles = (source: string, checks: string) => [
  { path: 'main.hpp', content: source },
  { path: 'lesson_test.cpp', content: `#include "main.hpp"\n#include <cassert>\n#include <iostream>\nint main() {\n${checks}\n  std::cout << "Practice checks passed\\n";\n}\n` }, compiledRunner('C++'),
]
export const javaPractice = [
  practiceLesson({ track: 'java', stage: 'fundamentals', title: 'Price a museum ticket',
    summary: 'Translate an age-band policy into a validated Java method with exact boundary checks.',
    concepts: ['methods', 'conditionals', 'exceptions'],
    explanation: 'An ordered age policy is easier to reason about when invalid input is rejected before price bands are checked. Integer cents represent the charge exactly. Boundary tests reveal whether a comparison includes the intended birthday.',
    instructions: ['Implement public static int ticketCents(int age, boolean member) in Main.java. Reject ages below 0 or above 120 with IllegalArgumentException.', 'Children under 5 and members of any valid age enter free. Otherwise ages 5–17 cost 600 cents, 18–64 cost 1200, and 65–120 cost 800. Validate age even for members.'],
    hints: ['Do not let free membership bypass invalid-age validation.', 'Write the age bands in ascending order.', 'Check ages 4/5, 17/18 and 64/65.'],
    reflectionQuestions: ['Why should validation happen before membership handling?', 'Which boundary case would expose using > instead of >=?'],
    examples: [{ input: 'Main.ticketCents(17, false)', output: '600' }, { input: 'Main.ticketCents(65, false)', output: '800' }],
    files: javaFiles(`public class Main {\n  public static int ticketCents(int age, boolean member) {\n    // TODO: validate age and apply the price bands.\n    throw new UnsupportedOperationException("Complete the TODO before submitting");\n  }\n}\n`, `    int[][] cases = {{0,0},{4,0},{5,600},{17,600},{18,1200},{64,1200},{65,800},{120,800}};\n    for (int[] item : cases) { equal(Main.ticketCents(item[0], false), item[1]); equal(Main.ticketCents(item[0], true), 0); }\n    for (int age : new int[]{-1,121}) for (boolean member : new boolean[]{true,false}) {\n      try { Main.ticketCents(age, member); throw new AssertionError("Invalid age accepted"); }\n      catch (IllegalArgumentException expected) { /* expected */ }\n    }`), command,
    quality: 'Validates before applying clear, nonoverlapping price bands',
  }),
  practiceLesson({ track: 'java', stage: 'data-flow', title: 'Build an inventory report',
    summary: 'Aggregate available stock by SKU with Java records, collections, and independent return values.',
    concepts: ['records', 'maps', 'collections'],
    explanation: 'Records describe data without adding mutable setters. A map is a natural destination for a grouped report: repeated SKUs update one total. Returning a new result on every call prevents one caller’s changes from contaminating another report.',
    instructions: ['Keep Main.Stock(String sku, int quantity, boolean available). Implement quantities(List<Stock>) returning a new Map<String,Integer>. Sum quantities for available rows grouped by exact, case-sensitive SKU.', 'Quantities are nonnegative and totals fit int; SKU strings are nonempty. Include available zero-quantity SKUs, exclude unavailable-only SKUs, and leave the source list unchanged. Empty input returns an empty map; every call must return an independent result.'],
    hints: ['Use a fresh HashMap inside the method.', 'Map.merge can accumulate an existing or new SKU.', 'Do not create a key for a skipped row.'],
    reflectionQuestions: ['Why should the result not be a static shared map?', 'How does a record differ from a mutable Stock object for this task?'],
    examples: [{ input: '[Stock("pen",2,true), Stock("pen",3,true)]', output: '{pen=5}' }],
    files: javaFiles(`import java.util.*;\npublic class Main {\n  public record Stock(String sku, int quantity, boolean available) {}\n  public static Map<String,Integer> quantities(List<Stock> rows) {\n    // TODO: group available stock without changing rows.\n    throw new UnsupportedOperationException("Complete the TODO before submitting");\n  }\n}\n`, `    equal(Main.quantities(List.of()), Map.of());\n    var rows = List.of(new Main.Stock("pen",2,true), new Main.Stock("pen",3,true), new Main.Stock("Pen",1,true), new Main.Stock("book",9,false), new Main.Stock("empty",0,true));\n    equal(Main.quantities(rows), Map.of("pen",5,"Pen",1,"empty",0));\n    equal(rows.get(0).quantity(), 2);\n    var first = Main.quantities(rows);\n    var second = Main.quantities(rows);\n    if (first == second) throw new AssertionError("Reports share a mutable result");\n    equal(Main.quantities(List.of(new Main.Stock("x",1,false))), Map.of());`), command,
    quality: 'Uses a fresh map, typed records and exact SKU grouping without source mutation',
  }),
  practiceLesson({ track: 'java', stage: 'composition', title: 'Model a reservation workflow',
    summary: 'Use enums and explicit transitions to prevent illegal reservation states.',
    concepts: ['enums', 'state machines', 'validation'],
    explanation: 'A state machine makes permitted transitions explicit. Each event either moves the reservation to a defined state or is rejected; silently accepting illegal transitions can turn a cancelled booking into a confirmed one.',
    instructions: ['Implement transition(State, Event) using the provided enums. HOLD + CONFIRM → CONFIRMED; HOLD + CANCEL → CANCELLED; CONFIRMED + CANCEL → CANCELLED. Every other combination throws IllegalStateException.', 'Reject a null state or event with IllegalArgumentException. Do not add implicit transitions or return null. The function has no mutable global state.'],
    hints: ['List the full state/event table before coding.', 'Validate null separately from an illegal transition.', 'Use nested switches or explicit state/event conditions.'],
    reflectionQuestions: ['Why reject CONFIRM after cancellation rather than silently doing nothing?', 'How would adding an EXPIRED state change both code and tests?'],
    examples: [{ input: 'transition(HOLD, CONFIRM)', output: 'CONFIRMED' }, { input: 'transition(CANCELLED, CONFIRM)', output: 'IllegalStateException' }],
    files: javaFiles(`public class Main {\n  public enum State { HOLD, CONFIRMED, CANCELLED }\n  public enum Event { CONFIRM, CANCEL }\n  public static State transition(State state, Event event) {\n    // TODO: implement only the three permitted transitions.\n    throw new UnsupportedOperationException("Complete the TODO before submitting");\n  }\n}\n`, `    equal(Main.transition(Main.State.HOLD, Main.Event.CONFIRM), Main.State.CONFIRMED);\n    equal(Main.transition(Main.State.HOLD, Main.Event.CANCEL), Main.State.CANCELLED);\n    equal(Main.transition(Main.State.CONFIRMED, Main.Event.CANCEL), Main.State.CANCELLED);\n    for (var state : Main.State.values()) for (var event : Main.Event.values()) {\n      if (state == Main.State.HOLD || (state == Main.State.CONFIRMED && event == Main.Event.CANCEL)) continue;\n      try { Main.transition(state,event); throw new AssertionError("Illegal transition accepted"); } catch (IllegalStateException expected) {}\n    }\n    try { Main.transition(null,Main.Event.CANCEL); throw new AssertionError("Null state accepted"); } catch (IllegalArgumentException expected) {}\n    try { Main.transition(Main.State.HOLD,null); throw new AssertionError("Null event accepted"); } catch (IllegalArgumentException expected) {}`), command,
    quality: 'Encodes only legal transitions and distinguishes invalid input from illegal state',
  }),
]

export const cppPractice = [
  practiceLesson({ track: 'cpp', stage: 'fundamentals', title: 'Normalize assessment scores',
    summary: 'Clamp integer scores and map them into grade bands without losing boundary precision.',
    concepts: ['functions', 'conditionals', 'value semantics'],
    explanation: 'Clamping turns any integer into a supported interval. Grade classification should happen after normalization so negative or oversized scores follow the same policy. Small value-returning functions are easy to compose and test.',
    instructions: ['Implement int clampScore(int raw) to return 0 below zero, 100 above 100, and raw otherwise. Implement char grade(int raw) using the clamped value: A for 90–100, B for 75–89, C for 50–74, F below 50.', 'Keep functions in main.hpp and do not add main(). The supplied check file provides the program entry point.'],
    hints: ['Clamp by comparison, not by adding an offset that could overflow.', 'Check high grade thresholds before low ones.', 'Test each threshold and one point below it.'],
    reflectionQuestions: ['Why can arithmetic normalization overflow for extreme input?', 'What is gained by composing grade with clampScore?'],
    examples: [{ input: 'grade(75)', output: "'B'" }, { input: 'clampScore(-5)', output: '0' }],
    files: cppFiles(`#pragma once\n#include <stdexcept>\ninline int clampScore(int /*raw*/) {\n  // TODO: clamp the score.\n  throw std::logic_error("Complete the TODO before submitting");\n}\ninline char grade(int /*raw*/) {\n  // TODO: classify the normalized score.\n  throw std::logic_error("Complete the TODO before submitting");\n}\n`, `  assert(clampScore(-10)==0 && clampScore(0)==0 && clampScore(42)==42 && clampScore(100)==100 && clampScore(200)==100);\n  assert(grade(-1)=='F' && grade(49)=='F' && grade(50)=='C' && grade(74)=='C');\n  assert(grade(75)=='B' && grade(89)=='B' && grade(90)=='A' && grade(200)=='A');`), command,
    quality: 'Uses overflow-safe comparisons and composes small value-returning functions',
  }),
  practiceLesson({ track: 'cpp', stage: 'data-flow', title: 'Count normalized tags',
    summary: 'Aggregate ASCII tags with standard-library containers and const-correct input handling.',
    concepts: ['maps', 'strings', 'const references'],
    explanation: 'A const reference avoids copying an input collection while preventing accidental mutation. Normalizing a copied string before using it as a map key gives predictable grouping; a map also supplies deterministic key ordering.',
    instructions: ['Implement countTags(const std::vector<std::string>&) returning std::map<std::string,int>. Trim ASCII spaces from both ends, lowercase ASCII A–Z, ignore empty results, and count repeated normalized tags.', 'Input uses only ASCII letters, digits and spaces, and counts fit int. Internal spaces remain unchanged. Do not modify input.'],
    hints: ['Find the first and last non-space character before taking a substring.', 'Lowercase a copy of each tag, not the input string.', 'Incrementing map[key] begins a missing integer count at zero.'],
    reflectionQuestions: ['Why is const std::vector<std::string>& useful here?', 'What would change if normalization had to support all Unicode letters?'],
    examples: [{ input: 'countTags({" JS ","js"})', output: '{{"js",2}}' }],
    files: cppFiles(`#pragma once\n#include <map>\n#include <string>\n#include <vector>\n#include <stdexcept>\ninline std::map<std::string,int> countTags(const std::vector<std::string>& /*tags*/) {\n  // TODO: normalize copies and count nonempty tags.\n  throw std::logic_error("Complete the TODO before submitting");\n}\n`, `  assert(countTags({}).empty());\n  const std::vector<std::string> input={" JS ","js"," ","React","REACT ","A B","a  b","42"};\n  const auto original=input;\n  const std::map<std::string,int> expected={{"js",2},{"react",2},{"a b",1},{"a  b",1},{"42",1}};\n  assert(countTags(input)==expected);\n  assert(input==original);\n  assert(countTags({"", "   "}).empty());`), command,
    quality: 'Keeps input const and separates ASCII normalization from map aggregation',
  }),
  practiceLesson({ track: 'cpp', stage: 'composition', title: 'Validate a bounded task queue',
    summary: 'Compose capacity checks, duplicate prevention, and removal in a deterministic queue transition.',
    concepts: ['vectors', 'invariants', 'state transitions'],
    explanation: 'A bounded queue has invariants: unique task IDs, stable order and a maximum size. A pure transition can return either a changed copy or an unchanged value while keeping each validation rule explicit.',
    instructions: ['Implement updateQueue(const std::vector<int>& ids, const std::string& action, int id, int capacity). Inputs contain unique positive IDs; capacity is nonnegative and ids.size() <= capacity.', 'For "add", append a positive ID only when it is absent and there is spare capacity. For "remove", remove the matching ID if present, preserving order. Unknown actions, nonpositive IDs, duplicate adds, missing removals and full queues return unchanged values.', 'Return a new vector value without changing the input. Keep the supplied function signature.'],
    hints: ['Decide whether the requested transition is valid before editing a copy.', 'std::find can locate both duplicates and removal targets.', 'Test capacity zero and a removal followed by a valid add.'],
    reflectionQuestions: ['Which invariants must hold after every transition?', 'How would the API differ if a rejected transition needed a reason code?'],
    examples: [{ input: 'updateQueue({1,2}, "add", 3, 2)', output: '{1,2}' }, { input: 'updateQueue({1,2}, "remove", 1, 2)', output: '{2}' }],
    files: cppFiles(`#pragma once\n#include <algorithm>\n#include <string>\n#include <vector>\n#include <stdexcept>\ninline std::vector<int> updateQueue(const std::vector<int>& /*ids*/, const std::string& /*action*/, int /*id*/, int /*capacity*/) {\n  // TODO: preserve queue invariants in every transition.\n  throw std::logic_error("Complete the TODO before submitting");\n}\n`, `  const std::vector<int> original={1,2};\n  assert((updateQueue(original,"add",3,3)==std::vector<int>{1,2,3}));\n  assert(updateQueue(original,"add",3,2)==original);\n  assert(updateQueue(original,"add",2,3)==original);\n  assert((updateQueue(original,"remove",1,2)==std::vector<int>{2}));\n  assert(updateQueue(original,"remove",9,2)==original);\n  assert(updateQueue(original,"other",3,3)==original);\n  assert(updateQueue(original,"add",0,3)==original);\n  assert(updateQueue({},"add",1,0).empty());\n  assert((original==std::vector<int>{1,2}));`), command,
    quality: 'Preserves uniqueness, capacity and ordering without mutating input',
  }),
]
