import { practiceLesson } from './shared'

const command = { executable: 'npm', args: ['test', '--', '--run'] }
const preparation = 'Run npm install once (and again after sandbox restoration). Run npm run dev to serve the React preview on port 3000; npm test runs the visible interaction checks.'
export function reactLessonFiles(source: string, tests: string) {
  return [
    { path: 'src/App.jsx', content: source },
    { path: 'src/main.jsx', content: `import React from 'react'\nimport { createRoot } from 'react-dom/client'\nimport App from './App.jsx'\nimport './style.css'\n\ncreateRoot(document.getElementById('root')).render(<React.StrictMode><App /></React.StrictMode>)\n` },
    { path: 'src/style.css', content: `:root { color-scheme: light dark; font-family: system-ui, sans-serif; }\nbody { margin: 0; }\nmain { max-width: 40rem; margin: 3rem auto; padding: 1rem; }\nbutton, input { font: inherit; margin: .4rem; padding: .6rem; }\n:focus-visible { outline: 3px solid currentColor; outline-offset: 3px; }\n` },
    { path: 'index.html', content: '<!doctype html>\n<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>CodeTutor practice</title></head><body><div id="root"></div><script type="module" src="/src/main.jsx"></script></body></html>\n' },
    { path: 'package.json', content: JSON.stringify({ private: true, type: 'module', scripts: { dev: 'vite --host 0.0.0.0 --port 3000', build: 'vite build', test: 'vitest' }, dependencies: { react: '19.2.8', 'react-dom': '19.2.8' }, devDependencies: { vite: '8.2.2', vitest: '4.1.10', jsdom: '30.0.1', '@testing-library/react': '16.3.2' } }, null, 2) + '\n' },
    { path: 'vite.config.js', content: `import { defineConfig } from 'vitest/config'\nexport default defineConfig({ test: { environment: 'jsdom', include: ['lesson.test.jsx'] } })\n` },
    { path: 'lesson.test.jsx', content: `import React from 'react'\nimport { afterEach, expect, test, vi } from 'vitest'\nimport { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'\nimport App from './src/App.jsx'\nafterEach(() => { cleanup(); vi.restoreAllMocks() })\n\n${tests}\n` },
  ]
}
export const reactPractice = [
  practiceLesson({ track: 'react', stage: 'fundamentals', title: 'Build an accessible counter',
    summary: 'Connect React state to labeled controls and announce a count with safe upper and lower bounds.',
    concepts: ['React state', 'events', 'accessibility'],
    explanation: 'State is the source of truth for both displayed values and button availability. Functional state updates use the latest count, even when events occur quickly. Native buttons provide keyboard behavior, while a status region announces changes without moving focus.',
    instructions: ['Implement App in src/App.jsx. Start at 0. Render buttons named "Decrease", "Increase", and "Reset", and exactly one role="status" element containing "Count: N".', 'Clamp the count to 0–10. Disable Decrease at 0 and Increase at 10. Reset returns to 0. Use React state and native buttons; do not directly mutate the DOM.'],
    hints: ['Derive disabled properties from the count.', 'Use a functional updater when the next count depends on the previous count.', 'A role="status" element provides a polite live announcement.'],
    reflectionQuestions: ['Why should disabled state be derived rather than stored separately?', 'What keyboard behavior do native buttons provide for free?'],
    examples: [{ input: 'Increase twice from initial state', output: 'Count: 2' }, { input: 'Reset at 10', output: 'Count: 0; Decrease disabled' }],
    files: reactLessonFiles(`import React, { useState } from 'react'\nexport default function App() {\n  // TODO: implement the accessible bounded counter.\n  throw new Error('Complete the TODO before submitting')\n}\n`, `test('initial state and native controls', () => {\n  render(<App />)\n  expect(screen.getByRole('status').textContent).toBe('Count: 0')\n  expect(screen.getByRole('button', {name:'Decrease'}).disabled).toBe(true)\n  expect(screen.getByRole('button', {name:'Increase'}).tagName).toBe('BUTTON')\n})\ntest('increments, bounds and resets', () => {\n  render(<App />)\n  for (let i=0;i<12;i++) fireEvent.click(screen.getByRole('button',{name:'Increase'}))\n  expect(screen.getByRole('status').textContent).toBe('Count: 10')\n  expect(screen.getByRole('button',{name:'Increase'}).disabled).toBe(true)\n  fireEvent.click(screen.getByRole('button',{name:'Decrease'}))\n  expect(screen.getByRole('status').textContent).toBe('Count: 9')\n  fireEvent.click(screen.getByRole('button',{name:'Reset'}))\n  expect(screen.getByRole('status').textContent).toBe('Count: 0')\n  fireEvent.click(screen.getByRole('button',{name:'Decrease'}))\n  expect(screen.getByRole('status').textContent).toBe('Count: 0')\n})`), command, preparation,
    quality: 'Uses React state, native labeled buttons and one polite status region',
  }),
  practiceLesson({ track: 'react', stage: 'data-flow', title: 'Filter a product list',
    summary: 'Derive a filtered list from controlled inputs without keeping duplicated result state.',
    concepts: ['controlled inputs', 'derived state', 'lists'],
    explanation: 'A filtered view is derived from products and the current query. Keeping the results in separate state can make them stale when products change. Compute them while rendering and use stable product IDs as keys.',
    instructions: ['Implement App({products}) with a text input labeled "Search products" and checkbox labeled "In stock only". Products have {id,name,inStock}; default products are supplied in the starter.', 'Match trimmed search text against names, case-insensitively. When checked, exclude out-of-stock products. Render each matching name in a list item. Show "No products found" if empty, and a role="status" element with "N products" (including "1 products").', 'Respond to changed products props without clearing the user’s filters. Do not mutate products or store a second copy of filtered results in state.'],
    hints: ['Store query and checkbox state, not the result array.', 'Apply both predicates to each product.', 'Use product.id as the list-item key.'],
    reflectionQuestions: ['How could storing filtered results in state become stale?', 'Why is the product ID a better key than its array index?'],
    examples: [{ input: 'Query " pen " over Pencil and Notebook', output: 'Pencil only' }],
    files: reactLessonFiles(`import React, { useState } from 'react'\nconst initialProducts = [{id:'1',name:'Pencil',inStock:true},{id:'2',name:'Notebook',inStock:false}]\nexport default function App({ products = initialProducts }) {\n  // TODO: derive an accessible filtered view from products and controls.\n  throw new Error('Complete the TODO before submitting')\n}\n`, `const products=[{id:'a',name:'Pencil',inStock:true},{id:'b',name:'Pen case',inStock:false},{id:'c',name:'Notebook',inStock:true}]\ntest('combines filters and handles no results', () => {\n  render(<App products={products} />)\n  expect(screen.getAllByRole('listitem')).toHaveLength(3)\n  fireEvent.change(screen.getByLabelText('Search products'),{target:{value:' PEN '}})\n  expect(screen.getAllByRole('listitem').map(x=>x.textContent)).toEqual(['Pencil','Pen case'])\n  fireEvent.click(screen.getByLabelText('In stock only'))\n  expect(screen.getByRole('status').textContent).toBe('1 products')\n  fireEvent.change(screen.getByLabelText('Search products'),{target:{value:'zzz'}})\n  expect(screen.queryAllByRole('listitem')).toHaveLength(0)\n  expect(screen.getByText('No products found')).toBeTruthy()\n})\ntest('new props use existing filters without mutation', () => {\n  const input=Object.freeze(products.map(x=>Object.freeze({...x})))\n  const view=render(<App products={input} />)\n  fireEvent.change(screen.getByLabelText('Search products'),{target:{value:'pen'}})\n  view.rerender(<App products={[...input,{id:'d',name:'Pen refill',inStock:true}]} />)\n  expect(screen.getAllByRole('listitem')).toHaveLength(3)\n  expect(screen.getByLabelText('Search products').value).toBe('pen')\n  expect(input).toHaveLength(3)\n})`), command, preparation,
    quality: 'Derives results from props and controlled filters with stable list keys',
  }),
  practiceLesson({ track: 'react', stage: 'composition', title: 'Keep asynchronous search current',
    summary: 'Handle loading, empty and failure states while preventing an older request from replacing newer results.',
    concepts: ['effects', 'async state', 'race conditions'],
    explanation: 'Responses can arrive in a different order from requests. An effect cleanup flag or request identity must fence both success and failure updates. Resetting status when the query changes also stops old results from masquerading as the current answer.',
    instructions: ['Implement App({search}) with an input labeled "Search". For every changed nonempty trimmed query, call search(query), which returns a Promise of {id,name} results. On empty query do not call search, clear results and show "Type to search" in role="status".', 'For a pending query clear old results and show "Searching…" in role="status". On success render result names as list items and status "N results"; on failure show "Search failed" in role="alert" and status "Try another query".', 'Only the latest query may update UI. Ignore old successes and failures after a new query, a cleared query, or unmount. No debounce is required. The starter’s demo search needs no network credentials.'],
    hints: ['Associate effect cleanup with the query that started the request.', 'Fence both then and catch handlers, not just successful results.', 'Clearing the input must also invalidate an in-flight response.'],
    reflectionQuestions: ['Why does awaiting a promise not prevent stale UI results?', 'Why must cleanup protect the failure handler as well as the success handler?'],
    examples: [{ input: 'Search "old", then "new"; "old" resolves last', output: 'Only results for "new" remain visible' }],
    files: reactLessonFiles(`import React, { useEffect, useState } from 'react'\nconst demoSearch = async query => [{id:'1',name:'React'},{id:'2',name:'TypeScript'},{id:'3',name:'Python'}].filter(item=>item.name.toLowerCase().includes(query.toLowerCase()))\nexport default function App({ search = demoSearch }) {\n  // TODO: implement query-scoped loading, results and failure states.\n  throw new Error('Complete the TODO before submitting')\n}\n`, `const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}}\ntest('empty, loading, failure and recovery', async () => {\n  const pending=deferred(), search=vi.fn().mockReturnValueOnce(pending.promise).mockResolvedValueOnce([])\n  render(<App search={search} />)\n  expect(screen.getByRole('status').textContent).toBe('Type to search')\n  expect(search).not.toHaveBeenCalled()\n  fireEvent.change(screen.getByLabelText('Search'),{target:{value:' bad '}})\n  await waitFor(()=>expect(search).toHaveBeenCalledWith('bad'))\n  expect(screen.getByRole('status').textContent).toBe('Searching…')\n  await act(async()=>pending.reject(new Error('failure')))\n  expect(screen.getByRole('alert').textContent).toBe('Search failed')\n  fireEvent.change(screen.getByLabelText('Search'),{target:{value:'good'}})\n  await waitFor(()=>expect(screen.getByRole('status').textContent).toBe('0 results'))\n  expect(screen.queryByRole('alert')).toBeNull()\n})\ntest.each(['resolve','reject'])('ignores stale %s and clears an in-flight query', async outcome => {\n  const old=deferred(), current=deferred(), final=deferred()\n  const search=vi.fn().mockReturnValueOnce(old.promise).mockReturnValueOnce(current.promise).mockReturnValueOnce(final.promise)\n  const view=render(<App search={search} />)\n  fireEvent.change(screen.getByLabelText('Search'),{target:{value:'old'}})\n  fireEvent.change(screen.getByLabelText('Search'),{target:{value:'new'}})\n  await act(async()=>current.resolve([{id:'new',name:'Newest'}]))\n  await act(async()=>old[outcome](outcome==='resolve'?[{id:'old',name:'Stale'}]:new Error('old failure')))\n  expect(screen.getByRole('listitem').textContent).toBe('Newest')\n  expect(screen.queryByRole('alert')).toBeNull()\n  fireEvent.change(screen.getByLabelText('Search'),{target:{value:'last'}})\n  fireEvent.change(screen.getByLabelText('Search'),{target:{value:' '}})\n  await act(async()=>final.resolve([{id:'last',name:'Discard me'}]))\n  expect(screen.queryAllByRole('listitem')).toHaveLength(0)\n  expect(screen.getByRole('status').textContent).toBe('Type to search')\n  view.unmount()\n})`), command, preparation,
    quality: 'Scopes success and failure updates to the latest query and cleans up effects',
  }),
]
