import { debugLesson } from '../practice/shared'
import { reactLessonFiles } from '../practice/react'

const command = { executable: 'npm', args: ['test', '--', '--run'] }
const preparation = 'Run npm install once, then npm test -- --run to reproduce the interaction failures. npm run dev serves the preview on port 3000; npm run build checks the production bundle.'
export const reactDebug = [
  debugLesson({ track: 'react', stage: 'state-bug', title: 'Make two queued increments count',
    summary: 'The “Add two” button only adds one. Diagnose how queued state updates use the rendered value.',
    concepts: ['debugging', 'React state', 'batched updates'],
    explanation: 'State values belong to a render. Two replacements based on that same captured value request the same next count, rather than composing two increments. Functional updaters receive the previous queued result and can therefore compose correctly.',
    instructions: ['Repair App in src/App.jsx. It starts at zero and renders a role="status" region containing "Count: N", an "Add two" button and a "Reset" button.', 'Every Add two click increases the count by exactly 2, including consecutive clicks. Reset returns to zero. Preserve the two queued increment operations so the exercise demonstrates functional updates rather than replacing them with one +2 assignment.'],
    hints: ['What value does count have during both setter calls?', 'Distinguish replacing state with a value from transforming queued state.', 'Use the updater form for both increments.'],
    reflectionQuestions: ['Why did calling the setter twice not double the increment?', 'How does a functional updater use the result of the preceding queued update?'],
    examples: [{ input: 'Click Add two twice', output: 'Count: 4' }],
    files: reactLessonFiles(`import React, { useState } from 'react'\nexport default function App() {\n  const [count, setCount] = useState(0)\n  function addTwo() {\n    setCount(count + 1)\n    setCount(count + 1)\n  }\n  return <main><p role="status">Count: {count}</p><button onClick={addTwo}>Add two</button><button onClick={() => setCount(0)}>Reset</button></main>\n}\n`, `test('initial state and reset remain usable',()=>{\n  render(<App />)\n  expect(screen.getByRole('status').textContent).toBe('Count: 0')\n  fireEvent.click(screen.getByRole('button',{name:'Reset'}))\n  expect(screen.getByRole('status').textContent).toBe('Count: 0')\n})\ntest('two queued updates compose on every click',()=>{\n  render(<App />)\n  fireEvent.click(screen.getByRole('button',{name:'Add two'}))\n  expect(screen.getByRole('status').textContent).toBe('Count: 2')\n  fireEvent.click(screen.getByRole('button',{name:'Add two'}))\n  expect(screen.getByRole('status').textContent).toBe('Count: 4')\n  fireEvent.click(screen.getByRole('button',{name:'Reset'}))\n  fireEvent.click(screen.getByRole('button',{name:'Add two'}))\n  expect(screen.getByRole('status').textContent).toBe('Count: 2')\n})`), command, preparation,
    quality: 'Composes both queued increments with updater functions and retains accessible controls',
  }),
  debugLesson({ track: 'react', stage: 'edge-cases', title: 'Keep notes attached to the right item',
    summary: 'Editing a note then reordering the list moves the note to another item. Find the unstable identity.',
    concepts: ['debugging', 'React keys', 'component identity'],
    explanation: 'A key identifies an item across renders, not merely its position. When index keys follow a reordered list, React may reuse an input’s DOM state for a different item. Stable item IDs keep local input edits associated with the intended record.',
    instructions: ['Repair App({items}) in src/App.jsx. Each item has unique id, name and note strings. Render a labeled text input "Note for NAME" initialized from note; edits stay with that ID when items are reordered or other IDs are removed.', 'Preserve each surviving input’s edited value across new props and the "Reverse order" button. A newly introduced ID uses its supplied note. Do not mutate items, clear all inputs, or convert input values into a shared state that mixes items.'],
    hints: ['Edit the first note and then reverse the list.', 'Compare the key assigned to an item before and after reordering.', 'Use the stable identifier supplied by the data rather than the render index.'],
    reflectionQuestions: ['Why can correct text labels still accompany the wrong input value?', 'What would random keys do to unsaved edits on every render?'],
    examples: [{ input: 'Edit Alpha’s note to "draft", then reverse Alpha/Beta', output: 'Alpha still contains "draft"; Beta keeps its original note' }],
    files: reactLessonFiles(`import React, { useState } from 'react'\nconst defaults = [{id:'a',name:'Alpha',note:'first'},{id:'b',name:'Beta',note:'second'}]\nexport default function App({ items = defaults }) {\n  const [reversed, setReversed] = useState(false)\n  const visible = reversed ? [...items].reverse() : items\n  return <main><button onClick={() => setReversed(value => !value)}>Reverse order</button><ul>{visible.map((item, index) => <li key={index}><label>Note for {item.name}<input defaultValue={item.note} /></label></li>)}</ul></main>\n}\n`, `const items=[{id:'a',name:'Alpha',note:'first'},{id:'b',name:'Beta',note:'second'}]\ntest('initial inputs use the corresponding notes',()=>{\n  render(<App items={items}/>)\n  expect(screen.getByLabelText('Note for Alpha').value).toBe('first')\n  expect(screen.getByLabelText('Note for Beta').value).toBe('second')\n})\ntest('reversing keeps edited notes attached to stable IDs',()=>{\n  render(<App items={Object.freeze(items.map(item=>Object.freeze({...item})))}/>)\n  fireEvent.change(screen.getByLabelText('Note for Alpha'),{target:{value:'draft'}})\n  fireEvent.click(screen.getByRole('button',{name:'Reverse order'}))\n  expect(screen.getByLabelText('Note for Alpha').value).toBe('draft')\n  expect(screen.getByLabelText('Note for Beta').value).toBe('second')\n})\ntest('new props remove and insert IDs without transferring old input state',()=>{\n  const view=render(<App items={items}/>)\n  fireEvent.change(screen.getByLabelText('Note for Beta'),{target:{value:'keep this'}})\n  view.rerender(<App items={[items[1],{id:'c',name:'Gamma',note:'new'}]}/>)\n  expect(screen.getByLabelText('Note for Beta').value).toBe('keep this')\n  expect(screen.getByLabelText('Note for Gamma').value).toBe('new')\n  expect(screen.queryByLabelText('Note for Alpha')).toBeNull()\n})`), command, preparation,
    quality: 'Uses stable record identity without discarding local edits during list changes',
  }),
]
